# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: hawaiihealingworks_development
  pool: 5
  username: HawaiiHealingWorks
  password:

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: hawaiihealingworks_test
  pool: 5
  username: HawaiiHealingWorks
  password:

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: hawaiihealingworks_production
  pool: 5
  username: HawaiiHealingWorks
  password: